-- NAMA: MARCO ALAND ADINANDA
-- NIU: 514817

-- VISUALISASI TABLE
SELECT * FROM DATA_MOBIL;
SELECT * FROM PELANGGAN;
SELECT * FROM SEWA_MOBIL;

-- 1
SELECT DATA_MOBIL.MERK_MOBIL, SEWA_MOBIL.NO_FAKTUR
FROM SEWA_MOBIL, DATA_MOBIL
WHERE DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL;

-- 2
SELECT PELANGGAN.NAMA_PELANGGAN, SEWA_MOBIL.NO_FAKTUR
FROM PELANGGAN LEFT JOIN SEWA_MOBIL
ON PELANGGAN.KODE_PELANGGAN = SEWA_MOBIL.KODE_PELANGGAN;

-- 3
SELECT DATA_MOBIL.JENIS_MOBIL, SEWA_MOBIL.NO_FAKTUR
FROM DATA_MOBIL LEFT JOIN SEWA_MOBIL
ON DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL;

-- 4
SELECT KODE_PELANGGAN, NAMA_PELANGGAN, TELEPON
FROM PELANGGAN
WHERE KODE_PELANGGAN = 'C-02';

-- 5
SELECT NO_FAKTUR, KODE_PELANGGAN, UANG_MUKA
FROM SEWA_MOBIL
WHERE UANG_MUKA > 500
ORDER BY UANG_MUKA DESC;

-- 6
SELECT DATA_MOBIL.KODE_MOBIL, DATA_MOBIL.MERK_MOBIL, SEWA_MOBIL.LAMA_PINJAM
FROM DATA_MOBIL, SEWA_MOBIL
WHERE DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL
	AND LAMA_PINJAM < 7;

-- 7
SELECT PELANGGAN.NAMA_PELANGGAN, DATA_MOBIL.MERK_MOBIL, SEWA_MOBIL.LAMA_PINJAM
FROM PELANGGAN, DATA_MOBIL, SEWA_MOBIL
WHERE PELANGGAN.KODE_PELANGGAN = SEWA_MOBIL.KODE_PELANGGAN
	AND DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL
	AND SEWA_MOBIL.LAMA_PINJAM < 7;
