-- NAMA: MARCO ALAND ADINANDA
-- NIU: 514817

-- VISUALISASI TABLE
SELECT * FROM DATA_MOBIL;
SELECT * FROM PELANGGAN;
SELECT * FROM SEWA_MOBIL;

-- 1
SELECT DATA_MOBIL.MERK_MOBIL, SEWA_MOBIL.NO_FAKTUR
FROM SEWA_MOBIL, DATA_MOBIL
WHERE DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL;

-- 2
SELECT PELANGGAN.NAMA_PELANGGAN, SEWA_MOBIL.NO_FAKTUR
FROM PELANGGAN LEFT JOIN SEWA_MOBIL
ON PELANGGAN.KODE_PELANGGAN = SEWA_MOBIL.KODE_PELANGGAN;

-- 3
SELECT DATA_MOBIL.JENIS_MOBIL, SEWA_MOBIL.NO_FAKTUR
FROM DATA_MOBIL LEFT JOIN SEWA_MOBIL
ON DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL;

-- 4
SELECT KODE_PELANGGAN, NAMA_PELANGGAN, TELEPON
FROM PELANGGAN
WHERE KODE_PELANGGAN = 'C-02';

-- 5
SELECT NO_FAKTUR, KODE_PELANGGAN, UANG_MUKA
FROM SEWA_MOBIL
WHERE UANG_MUKA > 500
ORDER BY UANG_MUKA DESC;

-- 6
SELECT DATA_MOBIL.KODE_MOBIL, DATA_MOBIL.MERK_MOBIL, SEWA_MOBIL.LAMA_PINJAM
FROM DATA_MOBIL, SEWA_MOBIL
WHERE DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL
	AND LAMA_PINJAM < 7;

-- 7
SELECT PELANGGAN.NAMA_PELANGGAN, DATA_MOBIL.MERK_MOBIL, SEWA_MOBIL.LAMA_PINJAM
FROM PELANGGAN, DATA_MOBIL, SEWA_MOBIL
WHERE PELANGGAN.KODE_PELANGGAN = SEWA_MOBIL.KODE_PELANGGAN
	AND DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL
	AND SEWA_MOBIL.LAMA_PINJAM < 7;

-- 8
SELECT PELANGGAN.KOTA, SUM(SEWA_MOBIL.UANG_MUKA)
FROM PELANGGAN, SEWA_MOBIL
WHERE PELANGGAN.KODE_PELANGGAN = SEWA_MOBIL.KODE_PELANGGAN
GROUP BY PELANGGAN.KOTA;

-- 9
SELECT PELANGGAN.NAMA_PELANGGAN, MAX(SEWA_MOBIL.LAMA_PINJAM)
FROM PELANGGAN, SEWA_MOBIL
WHERE PELANGGAN.KODE_PELANGGAN = SEWA_MOBIL.KODE_PELANGGAN
GROUP BY PELANGGAN.NAMA_PELANGGAN;

-- 10
SELECT KOTA, COUNT(KODE_PELANGGAN)
FROM PELANGGAN
GROUP BY KOTA;

-- 11
SELECT NO_FAKTUR, TANGGAL_PINJAM, LAMA_PINJAM
FROM SEWA_MOBIL
WHERE (TANGGAL_PINJAM BETWEEN '2017-06-03' AND '2017-06-10')
	AND LAMA_PINJAM > 2;
-- bisa juga pakai >= dan <= untuk melihat efeknya

SELECT NO_FAKTUR, TANGGAL_PINJAM, LAMA_PINJAM
FROM SEWA_MOBIL
WHERE (TANGGAL_PINJAM >='2017-06-03' AND TANGGAL_PINJAM <= '2017-06-10')
	AND LAMA_PINJAM > 2;

-- 12
SELECT DATA_MOBIL.JENIS_MOBIL, COUNT(SEWA_MOBIL.NO_FAKTUR)
FROM DATA_MOBIL, SEWA_MOBIL
WHERE DATA_MOBIL.KODE_MOBIL = SEWA_MOBIL.KODE_MOBIL
GROUP BY DATA_MOBIL.JENIS_MOBIL;

-- 13
SELECT SEWA_MOBIL.NO_FAKTUR, DATA_MOBIL.JENIS_MOBIL, 
	DATA_MOBIL.TARIF_SEWA, SEWA_MOBIL.LAMA_PINJAM, 
	SEWA_MOBIL.UANG_MUKA, 
	(SEWA_MOBIL.LAMA_PINJAM*DATA_MOBIL.TARIF_SEWA) AS TOTAL_BAYAR
FROM SEWA_MOBIL, DATA_MOBIL
WHERE SEWA_MOBIL.KODE_MOBIL = DATA_MOBIL.KODE_MOBIL;

-- CONT'D
SELECT SEWA_MOBIL.NO_FAKTUR, DATA_MOBIL.JENIS_MOBIL, 
	DATA_MOBIL.TARIF_SEWA, SEWA_MOBIL.LAMA_PINJAM, 
	SEWA_MOBIL.UANG_MUKA, 
	(SEWA_MOBIL.LAMA_PINJAM * DATA_MOBIL.TARIF_SEWA) AS TOTAL_BAYAR,
	(SEWA_MOBIL.LAMA_PINJAM * DATA_MOBIL.TARIF_SEWA - SEWA_MOBIL.UANG_MUKA) AS KURANG_BAYAR 
FROM SEWA_MOBIL, DATA_MOBIL
WHERE SEWA_MOBIL.KODE_MOBIL = DATA_MOBIL.KODE_MOBIL;

-- CONT'D
SELECT SEWA_MOBIL.NO_FAKTUR, DATA_MOBIL.JENIS_MOBIL, 
	DATA_MOBIL.TARIF_SEWA, SEWA_MOBIL.LAMA_PINJAM, 
	SEWA_MOBIL.UANG_MUKA, 
	(SEWA_MOBIL.LAMA_PINJAM * DATA_MOBIL.TARIF_SEWA) AS TOTAL_BAYAR,
	(SEWA_MOBIL.LAMA_PINJAM * DATA_MOBIL.TARIF_SEWA - SEWA_MOBIL.UANG_MUKA) AS KURANG_BAYAR,
	CASE WHEN (SEWA_MOBIL.LAMA_PINJAM * DATA_MOBIL.TARIF_SEWA - SEWA_MOBIL.UANG_MUKA) = 0 THEN 'LUNAS'
		ELSE 'BELUM LUNAS'
	END AS STATUS_PEMBAYARAN
FROM SEWA_MOBIL, DATA_MOBIL
WHERE SEWA_MOBIL.KODE_MOBIL = DATA_MOBIL.KODE_MOBIL;

-- UJIAN AKAN MIRIP SEPERTI WORKSHOP HARI INI, BISA JUGA DIBALIK